config/routes.rb
Rails.application.routes.draw do
  root 'product_search#index'

  resources :product_search, only: [:index]

  namespace :admin do
    resources :search_results, path: 'cache'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_key.rb
class SearchKey < ApplicationRecord
  has_many :search_results, dependent: :destroy

	scope :of_key, ->(key) { where('key = ?', key).first }

  def self.exists_of? key
    SearchKey.where('key = ?', key).any?
  end

end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :search_key

end

app/controllers/admin/search_results_controller.rb
class Admin::SearchResultsController < ApplicationController

  def index
    @cache_results = SearchResult.all
  end

  def show
    @cache_result = get_record params[:id]
  end


  # def update
  #   @cache_result = get_record params[:id]
  #   unless @cache_result.blank?
  #     @cache_result.update!( model_params )
  #   end
  # end

  def destroy
    @cache_result = get_record params[:id]
    unless @cache_result.blank?
      @cache_key = SearchKey.find( @cache_result.search_key_id )
      if @cache_result.destroy
        @cache_key.destroy! if @cache_key.present?
      end
    end
    redirect_to action: :index
  end

  private
  def get_record id
    return nil if params[:id].blank?
    SearchResult.find( id )
  end

  def model_params
    params.permit(:id, :search_key_id, :offset, :search_total, :results)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/product_search_controller.rb
class ProductSearchController < ApplicationController
  # include SearchCache
  # GET /searches
  def index
    if params[:search]
      if SearchKey.exists_of?(params[:search]) 
        @items =  SearchKey.of_key(params[:search]).search_results.present? ? SearchKey.of_key(params[:search]).search_results.first.results : []
    	else
        params[:cache] = true
        @items =  Sem3SearchService.new(params).execute['results']
    	end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_search_helper.rb
module ProductSearchHelper
  def link_to_retailer(item)
    if item['sitedetails'].any?
      name = item['sitedetails'].first['name']
      url = item['sitedetails'].first['url']

      link_to(name, url)
    else
      '--'
    end
  end
end

app/views/admin/search_results/_item.html.slim
tr
  td
    = link_to( SearchKey.find( item.search_key_id ).try(:key), admin_search_result_path(item) )
  td
    = truncate(item.results['results'].to_s, length: 70, omission: ' ...')
  td
    = Time.parse(item.updated_at.to_s).strftime('%Y-%m-%d, %H:%M:%S') 
  td
    = link_to 'delete', admin_search_result_path(item), method: :delete, data: { confirm: 'Confirming you want to delete this item?' }

app/views/admin/search_results/index.html.slim
.container
  .pull-right
    =link_to 'product search', product_search_index_path
  - if @cache_results.blank?
    h3
      | There are no cached results yet
  - else
    table.table.table-striped
      thead
        tr
          th 
            | Search Key
          th
            | Results
          th
            | Searched On
          th
            | Remove from cache

      tbody
        - @cache_results.each do |item|
        	=render partial: 'item', locals: { item: item }
              

app/views/admin/search_results/show.html.slim
.container
  .pull-right
    =link_to 'back to cache list', admin_search_results_path
  - if @cache_result.blank?
    h3
      | There are no cached results matching this record
  - else
    table.table.table-striped
      thead
        tr
          th 
            | Search Key
          th
            | Results
          th
            | Searched On
          th
            | Remove from cache

      tbody
		tr
		  td
		    = SearchKey.find( @cache_result.search_key_id ).try(:key)
		  td width= '65%'
		    = JSON.pretty_generate(JSON.parse(@cache_result.results['results'].to_json))
		  td
		    = Time.parse(@cache_result.updated_at.to_s).strftime('%Y-%m-%d, %H:%M:%S') 
		  td
		    = link_to 'delete', admin_search_result_path(@cache_result), method: :delete, data: { confirm: 'Confirming you want to delete this cache result?' }
              

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_search/index.html.slim
.container(style="margin-top: 1rem")
  = form_tag(product_search_index_path, method: :get, class: 'form-horizontal') do
    .form-group
      .col-md-9
        = text_field_tag :search, params[:search], class: 'form-control'
      .col-md-1
        = submit_tag 'Search', class: 'btn btn-primary'
      .col-md-2
        .pull-right
          =link_to 'admin', admin_search_results_path

.container
  - if @items.blank?
    h3
      | Nothing to see here... :( Try search again.
  - else
    table.table.table-striped
      thead
        tr
          th 
            | Name
          th
            | Retailer / Link
          th
            | Price

      tbody
        - @items['results'].each do |item|
          tr
            td
              = item['name']
            td
              = link_to_retailer(item)
            td
              = "$ #{item['price']}"        
              